name: Android CI

on:
  workflow_dispatch:
  push:
    branches: [ "master", "devel" ]
  pull_request:
    branches: [ "master", "devel" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    name: Android CI

    steps:
    - uses: actions/checkout@v4

    - name: Restore DLS Cache
      uses: actions/cache/restore@v4
      id: cache
      with:
        key: soundfont.dls
        path: ${{env.TEMP}}
        enableCrossOsArchive: true

    - name: Configure CMake
      run: |
        cmake -B ${{github.workspace}}/build \
            -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
            -DBUILD_TESTING=No \
            -DUSE_44KHZ=Yes \
            -DUSE_16BITS_SAMPLES=Yes \
            -DNEW_HOST_WRAPPER=Yes \
            -DCMAKE_TOOLCHAIN_FILE=${ANDROID_NDK}/build/cmake/android.toolchain.cmake \
            -DANDROID_ABI=x86_64 \
            -DANDROID_PLATFORM=android-35

    - name: Store DLS Cache
      if: steps.cache.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        key: soundfont.dls
        path: ${{env.TEMP}}
        enableCrossOsArchive: true

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
